security:
    role_hierarchy:

        ROLE_SFS_MEDIA_ADMIN_MEDIAS_RO:
            - PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_LIST
            - PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_DETAILS
        ROLE_SFS_MEDIA_ADMIN_MEDIAS_RW:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_RO
            - PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_CREATE
            - PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_DELETE
            - PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_UPDATE

        # DEPRECATED ROLES, WILL BE REMOVED IN 6.0
        # 5.1 REQUIRES PERMISSIONS-BUNDLE
        PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_LIST:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_LIST
        PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_DETAILS:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_DETAILS
        PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_CREATE:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_CREATE
        PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_DELETE:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_DELETE
        PERMISSION_SFS_MEDIA_ADMIN_MEDIAS_UPDATE:
            - ROLE_SFS_MEDIA_ADMIN_MEDIAS_UPDATE