name: Lint Code Base

on:
    push:
        branches: [ 5.5 ]
    pull_request:
        branches: [ 5.5 ]
        
jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
